### ISSUE TITLE
Cetus MK2 conversion instructions and files

### ISSUE THREAD

**Issue by mtchetch** [CNCKitchen/CetusMK3_RRF#1]
Hi,

You inspired me to convert my Cetus MK2 Extended to the E3 Fly Pro V3 board and RRF firmware. It has been a fun project and I wanted to contribute back to the community. Since you have positioned yourself as the goto Cetus converter, it would be nice to add my Cetus mk2 stuff to yours so people have an easier time embarking on such a project. 

I have a pullrequest riding on the gloomy community configs repository: https://github.com/TeamGloomy/LPC-STM32-RRFUserConfigs/pull/28

I included some rudimentary documentation and pinouts that could be helpfull. Any ideas on the best way forward?

**Comment by CNCKitchen** [comment]
I'll link to your config here and on my website.

**Comment by mtchetch** [comment]
That would be nice and probably helpful to others if someone wants to convert their Cetus MK2. I will add more photos to the docs later on when I have the time.
